/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProfileCollection } from "./ProfileCollection";
export * as factories from "./factories";
export { ProfileCollection__factory } from "./factories/ProfileCollection__factory";
